version: '3.8'

services:
  gofiber:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: postgres   
      DB_PORT: 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
